name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1-self-hosted
      if: ${{ false }}
      with:
        azure_static_web_apps_api_token: test
        repo_token: test # Used for Github integrations (i.e. PR comments)
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "/docfx_project/_site" # App source code path
        api_location: "" # Api source code path - optional
        output_location: "" # Built app content directory - optional
        skip_app_build: true
        skip_api_build: true
        ###### End of Repository/Build Configurations ######